# Generated by Django 4.1.3 on 2023-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
